
export enum EventType {
  IMPORTED = 'IMPORTED', // From ICS or external
  MANUAL = 'MANUAL',     // User manually added
  AI_WORK_SESSION = 'AI_WORK_SESSION' // Generated by Engine
}

export type Priority = 'High' | 'Medium' | 'Low';
export type EnergyLevel = 'High' | 'Low';
export type TaskCategory = 'Task' | 'Meeting' | 'Habit';

export interface CalendarEvent {
  id: string;
  title: string;
  start: Date;
  end: Date;
  type: EventType;
  description?: string;
  location?: string; // Added Location
  relatedTaskId?: string; 
  color?: string;
  priority?: Priority;
  isClass?: boolean; // New property to identify classes
  isGhost?: boolean; // New property for Optimistic UI loading state
}

export interface TaskFile {
  name: string;
  size: number;
  type: string;
  url?: string; 
}

export interface Task {
  id: string;
  category: TaskCategory; // New: Distinguish between types
  title: string;
  description: string;
  location?: string; // Added Location
  
  // -- Task Specific --
  difficulty: number; 
  totalHoursNeeded: number;
  deadline: Date;
  isCompleted?: boolean; // New status field
  
  // -- Habit Specific --
  recurrenceEndDate?: Date; // When the habit stops repeating
  
  // -- Meeting Specific --
  meetingDate?: string; // YYYY-MM-DD
  meetingStartTime?: string; // HH:mm
  meetingEndTime?: string; // HH:mm

  // -- Shared Scheduling Preferences --
  preferredDays: string[]; 
  preferredTimeStart: string; 
  preferredTimeEnd: string;
  preferredSessionDuration: number; 
  
  files: TaskFile[];
  isScheduled: boolean;
  priority: Priority;
  energyLevel: EnergyLevel;
}

export interface AIScheduleSuggestion {
  sessions: {
    startISO: string;
    endISO: string;
    summary: string;
    reasoning: string;
  }[];
}

export interface AIClassClassification {
  classEventIds: string[];
}
